import {
  Activity,
  AlertTriangle,
  ArrowRight,
  Barcode,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  Copyright,
  Cpu,
  CreditCard,
  File,
  FileText,
  Github,
  Handshake,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideShoppingBag,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Ruler,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  UserCircle2Icon,
  UserPen,
  UserX2Icon,
  Wallet,
  X,
} from "lucide-react";

export const Icons = {
  activity: Activity,
  barcode: Barcode,
  copyright: Copyright,
  cpu: Cpu,
  handshake: Handshake,
  ruler: Ruler,
  wallet: Wallet,
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  product: LucideShoppingBag,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  userPen: UserPen,
  user2: UserCircle2Icon,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  github: Github,
  twitter: Twitter,
  check: Check,
};
